# Setup
title:        Exijab Site
tagline:      A temporary message for now.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Elijah Heisenberg
  url:        exijab.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
